# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mywindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_view(object):
    def setupUi(self, view):
        view.setObjectName("view")
        view.setEnabled(True)
        view.resize(628, 218)
        self.centralwidget = QtWidgets.QWidget(view)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.correct_value = QtWidgets.QLabel(self.centralwidget)
        self.correct_value.setMaximumSize(QtCore.QSize(50, 10))
        self.correct_value.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.correct_value.setObjectName("correct_value")
        self.gridLayout.addWidget(self.correct_value, 1, 1, 1, 1)
        self.left_value = QtWidgets.QLabel(self.centralwidget)
        self.left_value.setMaximumSize(QtCore.QSize(50, 10))
        self.left_value.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_value.setObjectName("left_value")
        self.gridLayout.addWidget(self.left_value, 0, 1, 1, 1)
        self.correct = QtWidgets.QLabel(self.centralwidget)
        self.correct.setMaximumSize(QtCore.QSize(50, 10))
        self.correct.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.correct.setObjectName("correct")
        self.gridLayout.addWidget(self.correct, 1, 0, 1, 1)
        self.wrong_value = QtWidgets.QLabel(self.centralwidget)
        self.wrong_value.setMaximumSize(QtCore.QSize(50, 16777215))
        self.wrong_value.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.wrong_value.setObjectName("wrong_value")
        self.gridLayout.addWidget(self.wrong_value, 2, 1, 1, 1)
        self.total = QtWidgets.QLabel(self.centralwidget)
        self.total.setMaximumSize(QtCore.QSize(50, 10))
        self.total.setObjectName("total")
        self.gridLayout.addWidget(self.total, 3, 0, 1, 1)
        self.wrong = QtWidgets.QLabel(self.centralwidget)
        self.wrong.setMaximumSize(QtCore.QSize(50, 10))
        self.wrong.setObjectName("wrong")
        self.gridLayout.addWidget(self.wrong, 2, 0, 1, 1)
        self.total_value = QtWidgets.QLabel(self.centralwidget)
        self.total_value.setMaximumSize(QtCore.QSize(50, 16777215))
        self.total_value.setObjectName("total_value")
        self.gridLayout.addWidget(self.total_value, 3, 1, 1, 1)
        self.left = QtWidgets.QLabel(self.centralwidget)
        self.left.setMaximumSize(QtCore.QSize(50, 50))
        self.left.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left.setObjectName("left")
        self.gridLayout.addWidget(self.left, 0, 0, 1, 1)
        self.games = QtWidgets.QLabel(self.centralwidget)
        self.games.setMaximumSize(QtCore.QSize(50, 10))
        self.games.setObjectName("games")
        self.gridLayout.addWidget(self.games, 4, 0, 1, 1)
        self.games_value = QtWidgets.QLabel(self.centralwidget)
        self.games_value.setMaximumSize(QtCore.QSize(50, 16777215))
        self.games_value.setObjectName("games_value")
        self.gridLayout.addWidget(self.games_value, 4, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 0, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_2.addWidget(self.pushButton_11, 1, 3, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 2, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 0, 3, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_2.addWidget(self.pushButton_13, 0, 4, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 2, 4, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 1, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.new_2 = QtWidgets.QPushButton(self.centralwidget)
        self.new_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.new_2.setObjectName("new_2")
        self.horizontalLayout_2.addWidget(self.new_2)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.exit.setObjectName("exit")
        self.horizontalLayout_2.addWidget(self.exit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        view.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(view)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 628, 21))
        self.menubar.setObjectName("menubar")
        view.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(view)
        self.statusbar.setObjectName("statusbar")
        view.setStatusBar(self.statusbar)

        self.retranslateUi(view)
        self.exit.clicked.connect(view.close)
        QtCore.QMetaObject.connectSlotsByName(view)

    def retranslateUi(self, view):
        _translate = QtCore.QCoreApplication.translate
        view.setWindowTitle(_translate("view", "My Awesome Game - Reilaender"))
        self.correct_value.setText(_translate("view", "0"))
        self.left_value.setText(_translate("view", "15"))
        self.correct.setText(_translate("view", "korrekt"))
        self.wrong_value.setText(_translate("view", "0"))
        self.total.setText(_translate("view", "gesamt"))
        self.wrong.setText(_translate("view", "falsch"))
        self.total_value.setText(_translate("view", "0"))
        self.left.setText(_translate("view", "offen"))
        self.games.setText(_translate("view", "Spiele"))
        self.games_value.setText(_translate("view", "0"))
        self.label.setText(_translate("view", "Drücken Sie die Buttons in aufsteigender Richtung"))
        self.pushButton_4.setText(_translate("view", "6"))
        self.pushButton.setText(_translate("view", "3"))
        self.pushButton_2.setText(_translate("view", "9"))
        self.pushButton_3.setText(_translate("view", "7"))
        self.pushButton_5.setText(_translate("view", "13"))
        self.pushButton_9.setText(_translate("view", "15"))
        self.pushButton_8.setText(_translate("view", "1"))
        self.pushButton_7.setText(_translate("view", "4"))
        self.pushButton_6.setText(_translate("view", "11"))
        self.pushButton_11.setText(_translate("view", "8"))
        self.pushButton_12.setText(_translate("view", "12"))
        self.pushButton_10.setText(_translate("view", "10"))
        self.pushButton_13.setText(_translate("view", "14"))
        self.pushButton_15.setText(_translate("view", "2"))
        self.pushButton_14.setText(_translate("view", "5"))
        self.new_2.setText(_translate("view", "Neu"))
        self.exit.setText(_translate("view", "Ende"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    view = QtWidgets.QMainWindow()
    ui = Ui_view()
    ui.setupUi(view)
    view.show()
    sys.exit(app.exec_())

